name: Update Publications

permissions:
  contents: write

on:
  schedule:
    - cron: "0 3 */15 * *" # Runs at 3AM (UCT) every 10 days
  workflow_dispatch:  # Allows manual trigger of this workflow from the Actions tab

jobs:
  hugoblox:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests bibtexparser
          
      - name: Run publications update
        run: python update_publications.py
        
      - name: Commit changes
        # Set ID for `Check outputs` stage
        id: com
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'content: update publications'
          file_pattern: publications.bib 
